# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerprofile",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
