import { StyleSheet } from "react-native";
import { tokens } from "../../../styles/commonStyles";

const { colors, radius, fontWeights } = tokens;

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { paddingBottom: 130 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
  image: { width: "100%", height: 280, backgroundColor: colors.border },
  backButton: {
    position: "absolute",
    top: 48,
    left: 16,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.overlayDark,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    marginTop: 18,
    paddingHorizontal: 16,
    fontSize: 24,
    fontWeight: fontWeights.extraBold,
    color: colors.text,
  },
  location: {
    marginTop: 6,
    paddingHorizontal: 16,
    fontSize: 14,
    color: colors.textMuted,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  ratingText: {
    fontSize: 14,
    color: colors.textSecondary,
    fontWeight: fontWeights.semibold,
  },
  sectionTitle: {
    marginTop: 24,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: fontWeights.extraBold,
    color: colors.text,
  },
  description: {
    marginTop: 8,
    paddingHorizontal: 16,
    fontSize: 14,
    lineHeight: 21,
    color: colors.textSecondary,
  },
  infoBox: {
    marginHorizontal: 16,
    marginTop: 16,
    padding: 14,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 10,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  infoLabel: {
    fontSize: 13,
    color: colors.textMuted,
  },
  infoValue: {
    flex: 1,
    textAlign: "right",
    fontSize: 13,
    color: colors.text,
    fontWeight: fontWeights.bold,
  },
  optionCard: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    borderRadius: radius.lg,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
  },
  optionCardSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  optionCardDisabled: {
    opacity: 0.5,
  },
  optionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  optionText: {
    flex: 1,
  },
  optionName: {
    fontSize: 16,
    fontWeight: fontWeights.extraBold,
    color: colors.text,
  },
  optionSubText: {
    marginTop: 4,
    fontSize: 13,
    color: colors.textMuted,
  },
  optionPrice: {
    marginTop: 10,
    fontSize: 15,
    fontWeight: fontWeights.extraBold,
    color: colors.primary,
  },
  mutedText: {
    marginTop: 8,
    paddingHorizontal: 16,
    fontSize: 14,
    color: colors.textMuted,
  },
  bottomSpace: {
    height: 24,
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 16,
    paddingBottom: 24,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  priceBlock: {
    flex: 1,
  },
  priceLabel: { fontSize: 12, color: colors.textMuted },
  priceValue: { marginTop: 2, fontSize: 18, fontWeight: fontWeights.black, color: colors.text },
  bookButton: {
    height: 50,
    paddingHorizontal: 24,
    borderRadius: radius.lg,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  bookButtonDisabled: { opacity: 0.5 },
  bookButtonText: { fontSize: 15, fontWeight: fontWeights.black, color: colors.white },
  secondaryButton: {
    marginTop: 16,
    height: 46,
    paddingHorizontal: 20,
    borderRadius: radius.md,
    backgroundColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: { fontSize: 14, fontWeight: fontWeights.extraBold, color: colors.text },
});
