# Generated by Django 6.0.3 on 2026-05-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_payment_status_alter_booking_booking_status_and_more'),
        ('services', '0014_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='services.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.route'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.tourpackage'),
        ),
    ]
