# Generated by Django 6.0.3 on 2026-05-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_rooms_booking_route_booking_tour_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expire_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
