import { StyleSheet } from "react-native";
import { s, vs } from "react-native-size-matters";

export const accountStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 24,
  },
  contentContainer: {
    paddingBottom: vs(24),
  },
  profileCard: {
    marginTop: vs(10),
    padding: s(14),
    borderRadius: s(18),
    backgroundColor: "#FFFFFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: s(10),
  },
  profileLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: s(12),
    flex: 1,
  },
  profileText: {
    flex: 1,
    gap: vs(2),
  },
  name: {
    fontSize: vs(16),
    lineHeight: vs(20),
    fontWeight: "700",
    color: "#0F172A",
  },
  meta: {
    fontSize: vs(12),
    lineHeight: vs(16),
    color: "#64748B",
  },
  editPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: s(6),
    paddingHorizontal: s(10),
    paddingVertical: vs(8),
    borderRadius: s(999),
    backgroundColor: "rgba(15,23,42,0.06)",
  },
  editText: {
    fontSize: vs(12),
    fontWeight: "700",
    color: "#0F172A",
  },
  sectionShell: {
    marginTop: vs(12),
    borderRadius: s(18),
    backgroundColor: "#FFFFFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
  },
  row: {
    paddingHorizontal: s(14),
    paddingVertical: vs(12),
    flexDirection: "row",
    alignItems: "center",
    gap: s(12),
  },
  iconWrap: {
    width: s(36),
    height: s(36),
    borderRadius: s(12),
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  rowText: {
    flex: 1,
    gap: vs(2),
  },
  rowTitle: {
    fontSize: vs(13),
    lineHeight: vs(18),
    fontWeight: "800",
    color: "#0F172A",
  },
  rowSub: {
    fontSize: vs(12),
    lineHeight: vs(16),
    color: "#64748B",
  },
  divider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginLeft: s(14 + 36 + 12),
  },
  logoutButton: {
    marginTop: vs(14),
    borderRadius: s(18),
    paddingVertical: vs(12),
    paddingHorizontal: s(14),
    backgroundColor: "#FEF2F2",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: s(10),
  },
  logoutText: {
    fontSize: vs(13),
    lineHeight: vs(18),
    fontWeight: "900",
    color: "#991B1B",
    letterSpacing: 0.2,
  },
});