# Generated by Django 6.0.3 on 2026-04-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_seatstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='icon',
        ),
    ]
