# Generated by Django 6.0.3 on 2026-04-03 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_comment_travel_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='star_rating',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='available_rooms',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='total_rooms',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='included_services',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='traveltour',
            name='base_price',
        ),
        migrations.AddField(
            model_name='baseservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='baseservice',
            name='star_rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='services.traveltour'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='packages', to='services.package'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('total_beds', models.PositiveIntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='services.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='services.roomtype')),
            ],
        ),
    ]
