# Generated by Django 6.0.3 on 2026-04-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_seattype_provider'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='physicalseat',
            name='uniq_seat_per_transport',
        ),
        migrations.RemoveConstraint(
            model_name='seatstatus',
            name='uniq_seat_status_per_route',
        ),
        migrations.RemoveField(
            model_name='seatstatus',
            name='physical_seat',
        ),
        migrations.RemoveField(
            model_name='seatstatus',
            name='route',
        ),
        migrations.DeleteModel(
            name='PhysicalSeat',
        ),
        migrations.DeleteModel(
            name='SeatStatus',
        ),
    ]
