# Generated by Django 6.0.3 on 2026-04-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_physicalseat_uniq_seat_per_transport_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tourpackage',
            name='uniq_package_name_per_tour',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_package', to='services.traveltour'),
        ),
    ]
