# Generated by Django 6.0.3 on 2026-04-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0010_remove_tourpackage_uniq_package_name_per_tour_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='city',
            name='uniq_city_per_country',
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='locations.city'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
