# Generated by Django 6.0.3 on 2026-05-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_rooms_booking_route_booking_tour_package'),
        ('services', '0014_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_seats', to='services.seattype')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_seats', to='services.transport')),
            ],
        ),
        migrations.CreateModel(
            name='SeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=20)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_statuses', to='bookings.booking')),
                ('physical_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_statuses', to='services.physicalseat')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_statuses', to='services.route')),
            ],
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.AddConstraint(
            model_name='physicalseat',
            constraint=models.UniqueConstraint(fields=('transport', 'seat_number'), name='uniq_seat_per_transport'),
        ),
        migrations.AddConstraint(
            model_name='seatstatus',
            constraint=models.UniqueConstraint(fields=('route', 'physical_seat'), name='uniq_seat_status_per_route'),
        ),
    ]
