# Generated by Django 6.0.3 on 2026-06-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_unique_comment_user_travel_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='travel_tour',
        ),
    ]
