# Generated by Django 6.0.3 on 2026-06-06 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_description_city_image_city_is_active'),
        ('services', '0020_remove_wishlist_travel_tour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseservice',
            options={'verbose_name_plural': 'Base Services'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['display_order', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='seattype',
            name='uniq_seat_type_name_per_provider',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address_detail',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_beds',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='baseservice',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='baseservice',
            name='available_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseservice',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseservice',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baseservice',
            name='service_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('hotel', 'Hotel'), ('transport', 'Transport')], default='tour', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='total_beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='baseservice',
            name='star_rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='tour_packages', to='services.package'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='services.traveltour'),
        ),
        migrations.AddIndex(
            model_name='baseservice',
            index=models.Index(fields=['service_type', 'is_active'], name='services_ba_service_497932_idx'),
        ),
        migrations.AddIndex(
            model_name='baseservice',
            index=models.Index(fields=['provider', 'is_active'], name='services_ba_provide_951e09_idx'),
        ),
        migrations.AddConstraint(
            model_name='seattype',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='uniq_seat_type_per_provider'),
        ),
    ]
