# Generated by Django 6.0.3 on 2026-04-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Còn trống'), ('PENDING', 'Đang giữ chỗ'), ('BOOKED', 'Đã đặt')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='seattype',
            name='uniq_seat_type_per_transport',
        ),
        migrations.RemoveConstraint(
            model_name='tourpackage',
            name='uniq_package_title_per_tour',
        ),
        migrations.RenameField(
            model_name='tourpackage',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='transport',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='tourpackage',
            constraint=models.UniqueConstraint(fields=('tour', 'name'), name='uniq_package_name_per_tour'),
        ),
        migrations.AddField(
            model_name='physicalseat',
            name='seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_seats', to='services.seattype'),
        ),
        migrations.AddField(
            model_name='physicalseat',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_seats', to='services.transport'),
        ),
        migrations.AddField(
            model_name='route',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='services.city'),
        ),
        migrations.AddField(
            model_name='route',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='services.city'),
        ),
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='services.transport'),
        ),
        migrations.AddField(
            model_name='seatstatus',
            name='physical_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_statuses', to='services.physicalseat'),
        ),
        migrations.AddField(
            model_name='seatstatus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_statuses', to='services.route'),
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='transport',
        ),
        migrations.AddConstraint(
            model_name='physicalseat',
            constraint=models.UniqueConstraint(fields=('transport', 'seat_number'), name='uniq_seat_per_transport'),
        ),
        migrations.AlterUniqueTogether(
            name='seatstatus',
            unique_together={('route', 'physical_seat')},
        ),
    ]
