# Generated by Django 6.0.3 on 2026-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_physicalseat_route_seatstatus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatstatus',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transport',
            name='total_seats',
        ),
        migrations.AddConstraint(
            model_name='seatstatus',
            constraint=models.UniqueConstraint(fields=('route', 'physical_seat'), name='uniq_seat_status_per_route'),
        ),
    ]
