# Generated by Django 6.0.3 on 2026-04-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
    ]
