# Generated by Django 6.0.3 on 2026-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_country_continent_delete_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to='cities/'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
